config/routes.rb
Rails.application.routes.draw do

  root 'activity_finder#index'
  get '/result', to: 'activity_finder#result', as: 'result'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :activity_types
  resources :locations
  resources :attractions
  resources :users, except: [:new]
  get '/signup', to: 'users#new', as: 'new_user'
  get '/help', to: 'pages#help'
  get '/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :name, presence: true
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new, :create]
  # GET /users
  # GET /users.json
  def index
    @users = User.all.paginate(:page => params[:page], :per_page => 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @sidebar_names = sidebar_names
    @location = Location.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :name, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <p><%= form.label :username %></p>
    <p><%= form.text_field :username, id: :user_username %></p>
  </div>

  <div class="field">
    <p><%= form.label :name %></p>
    <p><%= form.text_field :name, id: :user_name %></p>
  </div>

  <div class="actions">
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit a user") %>
<div class = "form">
   <div class="text-div">
     <div class = "headings">
      <h1><b>Edit a User</b></h1>
     </div>
      <%= render 'form', user: @user %>

      <p><%= link_to 'Back', @user,  class: "buttonsm" %></p>
      <p></p>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "User index") %>
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class = form>
<%= will_paginate @user %>
</div>
<br>

<p align = center><%= link_to 'New User', new_user_path %></p>
<p align = center><%= link_to 'Create new attraction', new_attraction_path %></p>
<p align = center><%= link_to 'Create new location', new_location_path %></p>

app/views/users/new.html.erb
<% provide(:title, "New User") %>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class = form>
  <div class="text-div">
   <div class = "headings">
      <h1><b>Signup!</b></h1>
   </div>
<%= form_for @user do |f| %>

   <p> Name:</br> <%= f.text_field :name %></br></p>
   <p>UserName:</br> <%= f.text_field :username %></br></p>
   <p> Password:</br> <%= f.password_field :password %></br></p>
   <p>Password Confirmation:</br> <%= f.password_field :password_confirmation %></br></p>
  <p></p>
  <%= f.submit "Sign up", class: "button"%>
  <p></p>
    <% end %>

    <p><%= link_to 'Back', root_path, class: "buttonsm" %></p>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Dashboard") %>
  <style>
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
    .row.content {height: 450px}

    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 20px;
      background-color: #f1f1f1;
      height: 100%;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }

    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: auto;
        padding: 15px;
      }
      .row.content {height:auto;}
    }
  </style>
</head>
<body>
    <%= render 'layouts/sidebar', location: @location, sidebar_names: @sidebar_names %>

    <div class="col-sm-8 text-left">
     <div class="text-div">
      </br>
      <div class = "headings">
      <h3><b>User</b></h3>
      </div>
      <p id="notice"><%= notice %></p>
      <p>
         <strong>Username:</strong>
         <%= @user.username %>
      </p>
      <p>
      <strong>Name:</strong>
      <%= @user.name %>
      </p>
          <%= link_to 'Edit', edit_user_path(@user), class: "buttonsm" %></p>
      </br>
      </div>
      <hr>
      <%= render 'layouts/map_key' %>
      <hr>
      <div class = "headings">
      <h3><b>Holidays booked</b></h3>
      </div>
      </div>
      <div class="col-sm-8 text-left">
      <div class="col-sm-12 sidenav">
      <div class = "headings">
      <h3><b>Poseidon Resort</b></h3>
      </div>
      <%= image_tag "poseidon-resort.jpeg", :class => "image" %>
      <p></p>
      <div class = "headings">
      <h5><b>Overview</b></h5>
      </div>
      <p>Poseidon Resort is located just a 5-minute walk from the Levante beach, the old town and the centre of Benidorm. The hotel boasts 2 outdoor swimming pools. It is only a short walk to the nearest bars, shops and restaurants.</P>
      </br>
      <p>## For group bookings, please contact our sales team prior to booking to discuss your requirements. The hotel will only accept group bookings on…</p>
       <%= form_tag(locations_path) %>
        <%# @types.each do |typ| %>
        <%#= hidden_field_tag "activity_types[#{typ}]", %>
        <%# end %>
        <%= hidden_field_tag "activity_types_mirror" %>
        <%= hidden_field_tag "location[search]", "Calle del Esperanto, 9, 03503 Benidorm, Alicante, Spain" %>
       <p align = right><%= submit_tag "Plan Your Trip", class: "button"%></p>
       <%# end %>
      </div>
    </div>
  </div>
</div>
<script>
$("[id^=activity_types_types_]").change(function(){

    var oChecked = new Array();

    $("[id^=activity_types_types_]").each(function(index, val){
        if($(val).is(":checked"))
        oChecked.push($(val).val());
    });

    $("#activity_types_mirror").val(oChecked);
    console.log($('#activity_types_mirror').val())
});
</script>