config/routes.rb
Rails.application.routes.draw do

  root 'activity_finder#index'
  get '/result', to: 'activity_finder#result', as: 'result'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :activity_types
  resources :locations
  resources :attractions
  resources :users, except: [:new]
  get '/signup', to: 'users#new', as: 'new_user'
  get '/help', to: 'pages#help'
  get '/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  before_action :activity_type, only: [:show, :update, :edit, :destroy]

    # GET  activity_types
    # GET  activity_types.json
    def index
      @activity_types = ActivityType.all.paginate(:page => params[:page], :per_page => 10)
    end

    # GET  activity_types/1
    # GET  activity_types/1.json
    def show

    end

    # GET  activity_types/new
    def new
       @activity_type = ActivityType.new
    end

    # GET  activity_types/1/edit
    def edit

    end

    # POST  activity_types
    # POST  activity_types.json
    def create
       @activity_type = ActivityType.new (activity_type_params)

      respond_to do |format|
        if  @activity_type.save
          format.html { redirect_to  @activity_type, notice:  'activity_type was successfully created.' }
          format.json { render :show, status: :created, location:  @activity_type }
        else
          format.html { render :new }
          format.json { render json:  @activity_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT  activity_types/1
    # PATCH/PUT  activity_types/1.json
    def update
      respond_to do |format|
        if  @activity_type.update (activity_type_params)
          format.html { redirect_to  @activity_type, notice:  'activity_type was successfully updated.' }
          format.json { render :show, status: :ok, location:  @activity_type }
        else
          format.html { render :edit }
          format.json { render json:  @activity_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE  activity_types/1
    # DELETE  activity_types/1.json
    def destroy
       activity_type.destroy
      respond_to do |format|
        format.html { redirect_to activity_types_url, notice:  'activity_type was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def activity_type
         @activity_type = ActivityType.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def activity_type_params
        params.require(:activity_type).permit(:name)
      end
  end

app/helpers/activity_type_helper.rb
module ActivityTypeHelper
end

app/views/activity_types/_form.html.erb
<%= form_with(model: @activity_type, local: true) do |form| %>
  <% if @activity_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity_type.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @activity_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>
<div class = form>
<%= form_for @activity_type do |f| %>
Name:</br> <%= f.text_field :name :class => "border" %></br>
<p></p>
<%= f.submit %>
<p></p>
<% end %>
</div>

app/views/activity_types/edit.html.erb
<% provide(:title, "Edit an activity") %>

<h1 align = center>Editing activity type</h1>

<%= render 'form', activity_type: @activity_type %>


<p align = center><%= link_to 'Back', activity_types_path %></p>

app/views/activity_types/index.html.erb
<% provide(:title, "Index") %>

<h1 align = center>Activity Types</h1>

<table align = center border = 1>
<tr>
  <th>Activity type</th>
</tr>
  <% @activity_types.each do |activity| %>
    <tr> 
         <td><%= activity.name %></td>
         <td><%= link_to 'Show', activity %></td> 
         <td><%= link_to 'Edit', edit_activity_type_path(activity) %></td>
         <td><%= link_to 'Delete', activity, method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>
<div class = form>
<%= will_paginate @activity_types %>
</div>
<p align = center><%= link_to 'Create new activity', new_activity_type_path %></p>
<p align = center><%= link_to 'Create new attraction', new_attraction_path %></p>
<p align = center><%= link_to 'Create new location', new_location_path %></p>
<p align = center><%= link_to 'New User', new_user_path %></p>

app/views/activity_types/new.html.erb
<% provide(:title, "Create an activity") %>

<h1 align = center>Create an activity type</h1>

<%= render 'form', activity_type: @activity_type %>

<p align = center><%= link_to 'Back', activity_types_path %></p>

app/views/activity_types/show.html.erb
<% provide(:title, "Show an activity") %>
<div class = form>
<h1>Activity Type</h1>

<p><%= @activity_type.name %></p>

<p><%= link_to 'Back', activity_types_path %> ||
<%= link_to 'Edit', edit_activity_type_path(@activity_type) %></p>
</div>