config/routes.rb
Rails.application.routes.draw do

  root 'activity_finder#index'
  get '/result', to: 'activity_finder#result', as: 'result'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :activity_types
  resources :locations
  resources :attractions
  resources :users, except: [:new]
  get '/signup', to: 'users#new', as: 'new_user'
  get '/help', to: 'pages#help'
  get '/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
  has_and_belongs_to_many :attractions
  validates :address, uniqueness: { case_sensitive: false }
  validates :search, presence: true
  geocoded_by :search do |obj,results|
    if geo = results.first
      obj.name = geo.address.split(',').first.upcase
      obj.city    = geo.city.upcase
      obj.country = geo.country_code.upcase
      obj.latitude = geo.latitude
      obj.longitude = geo.longitude
      obj.address = geo.address.upcase
    end
  end
  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    before_action :location, only: [:show, :update, :edit, :destroy]
        # GET  Location
        # GET  location.json
        def index
          @locations = Location.all.paginate(:page => params[:page], :per_page => 10)
        end

        # GET  location/1
        # GET  location/1.json
        def show
          @icons = icon_urls
        end

        # GET  location/new
        def new
          @location = Location.new
        end

        # GET  location/1/edit
        def edit

        end

        # POST  location
        # POST  location.json
        def create
          #raise params.inspect
          @location = Location.new  (location_params)
          if @location.geocode
            if Location.exists?(address: @location.address)
              @foundloc = Location.find_by_address(@location.address)
              if type_params.empty? && mirror_params.empty?
                find_nearby_api(@foundloc, 5)
                redirect_to @foundloc
              elsif mirror_params.empty?
                find_nearby_api(@foundloc, 5, type_params)
                redirect_to result_path(location_id: @foundloc.id, display: type_params)
              else
                find_nearby_api(@foundloc, 5, mirror_params)
                redirect_to result_path(location_id: @foundloc.id, display: mirror_params)
              end
            else
              if @location.save
                if type_params.empty?
                  find_nearby_api(@location, 5)
                  redirect_to @location, notice: 'Location was successfully created.'
                else
                  find_nearby_api(@location, 5, type_params)
                  redirect_to result_path(location_id: @location.id, display: type_params)
                end
              else
                render :new
              end
            end
          else
            redirect_to root_path
          end
        end

        # PATCH/PUT  location/1
        # PATCH/PUT  location/1.json

        def update
          respond_to do |format|
            if  @location.update  (location_params)
              format.html { redirect_to  @location, notice:  'Location was successfully updated.' }
              format.json { render :show, status: :ok, location: @location }
            else
              format.html { render :edit }
              format.json { render json: @location.errors, status: :unprocessable_entity }
            end
          end
        end

        # DELETE  location/1
        # DELETE  location/1.json
        def destroy
          @location.destroy
          respond_to do |format|
            format.html { redirect_to locations_url, notice:   'Location was successfully destroyed.' }
            format.json { head :no_content }
          end
        end

        def find_nearby_api(location, radius_in_miles, search = search_types)
          @client ||= GooglePlaces::Client.new(Rails.application.secrets.api_key)
          new_attractions = @client.spots(location.latitude,location.longitude, :radius => radius_in_miles * 1600, :types => search)
          #open("#{location.address.parameterize}-#{Time.now.to_i}.txt", "w"){|f| f.write(new_attractions)          }
          new_attractions.each do |att|
            unless Attraction.exists?(place_id: att.id)
              new_params = {name: att.name, longitude: att.lng, latitude: att.lat, place_id: att.id}
              new_att = location.attractions.create!(new_params)
              if att.photos.any?
                new_att.photo_url = att.photos[0].fetch_url(800)
              end
              att.types.each do |type|
                if ActivityType.exists?(name: type)
                  new_type = ActivityType.find_by(name: type)
                elsif search_types.include?(type)
                  new_type = ActivityType.create!(name: type)
                end
                if new_type
                  new_type.attractions << new_att
                  new_type.save!
                end
              end
              new_att.save!
            else
              unless location.attractions.include?(Attraction.find_by_place_id(att.id))
                location.attractions << Attraction.find_by_place_id(att.id)
              end
            end
          end
          location.save!
        end


        private

          def search_types
            [
              'amusement_park',
              'aquarium',
              'art_gallery',
              'beauty_salon',
              'bar',
              'book_store',
              'bowling_alley',
              'casino',
              'church',
              'city_hall',
              'embassy',
              'hindu_temple',
              'meal_delivery',
              'meal_takeaway',
              'mosque',
              'movie_theater',
              'museum',
              'night_club',
              'place_of_worship',
              'restaurant',
              'shopping_mall',
              'spa',
              'stadium',
              'synagogue',
              'zoo',
            ]
          end

          # Use callbacks to share common setup or constraints between actions.s
          def location
            @location = Location.find(params[:id])
          end

          # Never trust parameters from the scary internet, only allow the white list through.
          def location_params
            params.require(:location).permit(:name,:search)
          end

          def type_params
            if params.include?(:activity_types)
              params[:activity_types][:types]
            else
              []
            end
          end
          def mirror_params
            if params.include?(:activity_types_mirror)
              params[:activity_types_mirror].split(',')
            else
              []
            end
          end
      end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: @location, local: true) do |form| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>
<div class = form>
<%= form_for @location do |f| %>
Name:</br> <%= f.text_field :name %></br>
Search:<br> <%= f.text_field :search %></br>
<p></p>
<%= f.submit %>
<p></p>
<% end %>
</div>

app/views/locations/edit.html.erb
<% provide(:title, "Edit a location") %>

<h1 align = center>Edit a location</h1>

<%= render 'form', location: @location %>


<p align = center><%= link_to 'Back', locations_path %></p>

app/views/locations/index.html.erb
<% provide(:title, "Index") %>
<div class = form>
<p> <h1> Locations Index </h1> </p>
<table align = center border = 1>
<tr>
  <th>name</th>
  <th>country</th>
  <th>longitude</th>
  <th>latitude</th>
</tr>
  <% @locations.each do |location| %>
    <tr>
        <td><%= location.name %></br></br>
        <td><%= location.country %></br></br>
        <td><%= location.longitude %></br></br>
        <td><%= location.latitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Delete', location, method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>
<div class = form>
<%= will_paginate @location %>
</div>
<p align = center><%= link_to 'Create new location', new_location_path %></p>
<p align = center><%= link_to 'Create new attraction', new_attraction_path %></p>
<p align = center><%= link_to 'New User', new_user_path %></p>
<p align = center><%= link_to 'Create new activity', new_activity_type_path %></p>
</div>

app/views/locations/new.html.erb
<% provide(:title, "Create a location") %>

<h1 align = center>Create a location</h1>

<%= render 'form', location: @location %>

<p align = center><%= link_to 'Back', locations_path %></p>

app/views/locations/show.html.erb
<% provide(:title, "Show a location") %>
<div class = "headings">
      <h2 align = center><b><%= @location.name %></b></h2>
      </div>
      </br>
      <table class = "loc-table" align = center >
      <tr>
      <td>Country:</td><td><%= @location.country %></td>
      </tr>
      <tr>
      <td>Longitude:</td><td><%= @location.longitude %></td>
      </tr>
      <tr>
      <td>Latitude:</td><td><%= @location.latitude %></td>
      </tr>
      <tr>
      <td>Address:</td><td><%= @location.address %></td>
      </tr>
      </table>
      <div class = form>
      <p></p>
      <p><%= link_to 'Back', root_path, class: "button" %></p>
      <hr>
      <div class = "headings">
      <h3><b>Map View</b></h3>
      </div>
      </div>
      <%= render 'layouts/map' %>
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  var circles = handler.addCircles(
  [{ lat: <%= @location.latitude %>, lng: <%= @location.longitude %>, radius: 5*1600 }],
  { strokeColor: '#FF0000', fillColor: '#888888'}
);
  markers = handler.addMarkers([
    {
      "lat": <%= @location.latitude %>,
      "lng": <%= @location.longitude %>
    },
    <% @location.attractions.each do |att| %>
    {
      "lat": <%= att.latitude %>,
      "lng": <%= att.longitude %>,
      "infowindow": "<a href='/attractions/<%= att.id %>'><%= att.name %></a>",
      "picture": {
          "url": "<%= image_url(@icons[att.activity_types.first.name])%>",
          "width": 20,
          "height": 34,
        },
    },
    <% end %>
  ]);
  handler.bounds.extendWith(markers);
  handler.bounds.extendWith(circles);
  handler.fitMapToBounds();
});
</script>