config/routes.rb
Rails.application.routes.draw do

  root 'activity_finder#index'
  get '/result', to: 'activity_finder#result', as: 'result'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  resources :activity_types
  resources :locations
  resources :attractions
  resources :users, except: [:new]
  get '/signup', to: 'users#new', as: 'new_user'
  get '/help', to: 'pages#help'
  get '/home', to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/attractions_controller.rb
class AttractionsController < ApplicationController
  before_action :attraction, only: [:show, :update, :edit, :destroy]

      # GET  attraction
      # GET  attractions.json
      def index
         @attractions = Attraction.all.paginate(:page => params[:page], :per_page => 10)
      end

      # GET  attractions/1
      # GET  attractions/1.json
      def show
        if @attraction.photo_url
          @photo = @attraction.photo_url
        else
          @photo = 'whut.jpg'
        end
      end

      # GET  attractions/new
      def new
          @attraction = Attraction.new
      end

      # GET  attractions/1/edit
      def edit

      end

      # POST  attractions
      # POST  attractions.json
      def create
          @attraction = Attraction.new  (attraction_params)

        respond_to do |format|
          if  @attraction.save
            format.html { redirect_to @attraction, notice:   'attraction was successfully created.' }
            format.json { render :show, status: :created, location:   @attraction }
          else
            format.html { render :new }
            format.json { render json: @attraction.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT  attractions/1
      # PATCH/PUT  attractions/1.json
      def update
        respond_to do |format|
          if  @attraction.update  (attraction_params)
            format.html { redirect_to  @attraction, notice:  'attraction was successfully updated.' }
            format.json { render :show, status: :ok, location: @attraction }
          else
            format.html { render :edit }
            format.json { render json: @attraction.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE  attractions/1
      # DELETE  attractions/1.json
      def destroy
        @attraction.destroy
        respond_to do |format|
          format.html { redirect_to attractions_url, notice:   'attraction was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def attraction
            @attraction = Attraction.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def attraction_params
          params.require(:attraction).permit(:name, :longitude, :latitude, :speciality)
        end
    end

app/helpers/attractions_helper.rb
module AttractionsHelper
end

app/views/attractions/_form.html.erb
<%= form_with(model: @attraction, local: true) do |form| %>
  <% if @attraction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attraction.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @attraction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% end %>
<div class = form>
<%= form_for @attraction do |f| %>
Name:</br> <%= f.text_field :name %></br>
Longitude:</br> <%= f.text_field :longitude %></br>
Latitide: </br><%= f.text_field :latitude %></br>
Speciality: </br><%= f.text_field :speciality %></br>
<p></p>
<%= f.submit %>
<p></p>
<% end %>
</div>

app/views/attractions/edit.html.erb
<% provide(:title, "Edit an attraction") %>

<h1 align = center>Editing attraction type</h1>

<%= render 'form', attraction: @attraction %>


<p align = center><%= link_to 'Back', attractions_path %></p>

app/views/attractions/index.html.erb
<% provide(:title, "Index") %>
<h1 align = center>Attractions Table</h1>
<table align = center border = 1>
<tr>
  <th>Attraction</th>
</tr>
  <% @attractions.each do |attraction| %>
    <tr> 
         <td><%= attraction.name %></br></br>
         <%= attraction.longitude %></br></br>
         <%= attraction.latitude %></br></br>
         <%= attraction.speciality %></td>
         <td><%= link_to 'Show', attraction %></td> 
         <td><%= link_to 'Edit', edit_attraction_path(attraction) %></td>
         <td><%= link_to 'Delete', attraction, method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
  <% end %>
</table>
<div class = form>
<%= will_paginate @attraction %>
</div>
<p align = center><%= link_to 'Create new attraction', new_attraction_path %></p>
<p align = center><%= link_to 'Create new location', new_location_path %></p>
<p align = center><%= link_to 'New User', new_user_path %></p>

app/views/attractions/new.html.erb
<% provide(:title, "Create an attraction") %>

<h1 align = center>Create an attraction type</h1>

<%= render 'form', attraction: @attraction %>

<p align = center><%= link_to 'Back', attractions_path %></p>

app/views/attractions/show.html.erb
<% provide(:title, "Show an attraction") %>

<div class="form">
<h1>Attraction</h1>
</br>
<table align = center>
<tr>
<td>Name: </td><td><%= @attraction.name %></td>
</tr>
<tr>
<td>Longitude:</td><td><%= @attraction.longitude %></td>
</tr>
<tr>
<td>Latitude:</td><td><%= @attraction.latitude %></td>
</tr>
<tr>
<td>Speciality</td><td><%= @attraction.speciality %></td>
</tr>
</table> 
<p><%= link_to 'Back', root_path %> <br>
<hr>
<hr>
  <% if @photo == "whut.jpg" %>
    <%= image_tag @photo %>
  <% else %>
    <img src= <%= @photo %> > </img>
  <% end %>
<hr>
</div>
<h3 align = center>Map View</h3>
 <%= render 'layouts/map' %>
<script>
handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  var circles = handler.addCircles(
  [{ lat: <%= @attraction.latitude %>, lng: <%= @attraction.longitude %>, radius: 5*1600 }],
  { strokeColor: '#FF0000', fillColor: '#888888'}
);
  markers = handler.addMarkers([
    {
      "lat": <%= @attraction.latitude %>,
      "lng": <%= @attraction.longitude %>,
      "infowindow": "<%= @attraction.name %>"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.bounds.extendWith(circles);
  handler.fitMapToBounds();
});
</script>